backend:
  name: git-gateway
  branch: main  # or whatever branch you want to use for editing content
  
media_folder: "images"  # where images will be uploaded
public_folder: "/images"  # the folder to access images from the site

collections:
  - name: "about"  # collection for the About section
    label: "About"
    files:
      - label: "About Me"
        name: "about-me"
        file: "_data/about-me.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "description", label: "Description", widget: "text" }

  - name: "projects"  # collection for the Projects section
    label: "Projects"
    files:
      - label: "ECommerce Backend Solution"
        name: "ecommerce-project"
        file: "_data/ecommerce-project.md"
        fields:
          - { name: "title", label: "Project Title", widget: "string" }
          - { name: "description", label: "Project Description", widget: "text" }
          - { name: "link", label: "Project Link", widget: "string" }
          - { name: "image", label: "Image", widget: "image" }
